### ISSUE TITLE
"Invalid instance id" error with Laravel backend

### ISSUE THREAD

**Issue by denishacks** [captcha-com/reactjs-captcha#1]
Guys, first of all, thank you for this long-awaited release :)
I've got `Invalid instance id` error with my Laravel backend cause there is missing `t` parameter in the "get captcha html" link `https://localhost/captcha-handler?get=html&c=SplashCaptcha`. Hope it will be compatible soon with Laravel

**Comment by botdetect-support** [comment]
@denisrocks 
Now you can use Laravel Captcha package as a backend for React app. 
Here is the where you can find BotDetect Captcha React Module integration guide (with Laravel on the backend): 
https://captcha.com/react-captcha.html?tabs=howto-server-side-validation-laravel
Please note that, to configure Captcha options in BotDetect's Simple API, you will need to create `botdetect.xml` file in your Laravel's config folder.
If you have further questions, please write to: support@captcha.com
